name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./... -o output/gobuild

    - name: Test
      run: go test -v ./...

    # package project files
    - name: compressive archive
      run: tar cvfz gobuild.tar.gz  output/gobuild
    - name: staging
      run: mkdir staging && mv gobuild.tar.gz staging/
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
